// src/components/Offcanvas.tsx
import { useState } from "react";
export default function Offcanvas({ children }: { children: any }) {
  let [show, setShow] = useState(false);

  const toggleChecked = () => setShow((value) => !value);

  function closeModal() {
    setShow(false);
  }

  function openModal() {
    setShow(true);
  }

  return (
    <>
      <div>
        <button
          type="button"
          onClick={closeModal}
          aria-label="Backdrop"
          className={`${
            !show ? "opacity-0 select-none pointer-events-none" : "opacity-100 pointer-events-auto"
          } fixed inset-0 bg-gray-900/60 duration-300 backdrop-blur w-full z-[60]`}
        />
        <button
          type="button"
          onClick={toggleChecked}
          className="right-2 offcanvasBtn cursor-pointer xl:hidden fixed text-lg justify-center items-center opacity-100 rounded-md overflow-hidden hover:opacity-100 p-0.5 bg-white/90 hover:bg-gray-200/90 duration-1000 font-medium text-gray-900  z-[60] flex top-4"
        >
          <span className="pl-3 pr-2 font-sans uppercase">Menú</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth="1.5"
            stroke="currentColor"
            className="w-8 h-8"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
            />
          </svg>
        </button>
        <div
          onClick={closeModal}
          className={`OffcanvasNav OffcanvasNavRight ${
            !show
              ? "translate-x-full pointer-events-none"
              : "translate-x-0 pointer-events-auto"
          } `}
        >
          <button
            type="button"
            onClick={closeModal}
            aria-label="Cerrar menú"
            className="absolute right-0 top-0 m-3"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 24 24"
            >
              <path
                fill="currentColor"
                d="M13.46 12L19 17.54V19h-1.46L12 13.46L6.46 19H5v-1.46L10.54 12L5 6.46V5h1.46L12 10.54L17.54 5H19v1.46L13.46 12Z"
              />
            </svg>
          </button>
          {children}
        </div>
      </div>
    </>
  );
}

// src/components/Navigation/Offcanvas.vue
<template>
  <div class="xl:hidden">
    <Transition
      enter-from-class="opacity-0"
      enter-active-class=""
      enter-to-class="opacity-100"
      leave-from-class="opacity-100"
      leave-active-class=""
      leave-to-class="opacity-0"
    >
      <button
        aria-hidden="true"
        class="fixed inset-0 z-40 bg-white/60 backdrop-blur"
        @click="show = !show"
        v-if="!show"
      />
    </Transition>
    <button
      id="menuOffcanvas"
      class="fixed text-lg justify-center items-center ring ring-indigo-600 p-1 sm:py-2 px-4 bg-white font-bold text-gray-900 right-2 z-[60] flex top-4 lg:top-3 rounded-lg"
      @click="show = !show"
    >
      <span >Menú</span>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="w-7 h-7"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
        />
      </svg>
    </button>
    <Transition
      enter-from-class="translate-x-full"
      enter-active-class=""
      enter-to-class="translate-x-0"
      leave-from-class="translate-x-0"
      leave-active-class=""
      leave-to-class="translate-x-full"
    >
      <div
        v-if="!show"
        class="OffcanvasNav OffcanvasNavRight border-l-2 border-gray-800/1  0  fixed right-0 text-center shadow-lg font-sans text-2xl space-y-12 top-0 bottom-0 bg-white duration-700 w-64 p-3 z-[60] flex justify-start pt-2 flex-col"
      >
        <slot />
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
const show = ref(true);
</script>

<style>
.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
